FROM ubuntu:20.04

LABEL maintainer="usuki"

SHELL ["/bin/bash", "-c"]

ENV TZ=Asia/Tokyo\
    DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y\
    npm\
    nodejs\
    git\
    bash-completion

RUN npm install -y yarn

RUN apt-get install -y language-pack-ja-base language-pack-ja locales

RUN echo ". /etc/bash_completion" >> ~/.bashrc

#localeを日本語設定に変更
RUN locale-gen ja_JP.UTF-8

#言語を日本語に設定
ENV LANG ja_JP.UTF-8
