FROM ubuntu:20.04

LABEL maintainer="usuki"

SHELL ["/bin/bash", "-c"]

ENV TZ=Asia/Tokyo\
    DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y\
    curl\
    gnupg\
    git\
    language-pack-ja-base\
    language-pack-ja\
    locales\
    bash-completion &&\
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&\
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list &&\
    apt update && apt install -y yarn &&\
    yarn global add n &&\
    n lts &&\
    echo ". /etc/bash_completion" >> ~/.bashrc

#localeを日本語設定に変更
RUN locale-gen ja_JP.UTF-8

#言語を日本語に設定
ENV LANG ja_JP.UTF-8
